name: Build Darsyar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Extract Darsyar project
        run: |
          unzip -q darsyar_final_mobile_ready.zip -d extracted

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable

      - name: Build APK
        run: |
          cd extracted/darsyar_final
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: darsyar-release-apk
          path: extracted/darsyar_final/build/app/outputs/flutter-apk/app-release.apk
